package ec.com.mochas.testws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-08T16:52:47.144-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soap.ws.mochas.ec.com/", name = "ITestWs")
@XmlSeeAlso({ObjectFactory.class})
public interface ITestWs {

    @WebMethod
    @RequestWrapper(localName = "productos", targetNamespace = "http://soap.ws.mochas.ec.com/", className = "ec.com.mochas.testws.Productos")
    @ResponseWrapper(localName = "productosResponse", targetNamespace = "http://soap.ws.mochas.ec.com/", className = "ec.com.mochas.testws.ProductosResponse")
    @WebResult(name = "listaProductos", targetNamespace = "")
    public java.util.List<ec.com.mochas.testws.Producto> productos();

    @WebMethod
    @RequestWrapper(localName = "saludar", targetNamespace = "http://soap.ws.mochas.ec.com/", className = "ec.com.mochas.testws.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://soap.ws.mochas.ec.com/", className = "ec.com.mochas.testws.SaludarResponse")
    @WebResult(name = "saludo", targetNamespace = "")
    public java.lang.String saludar(
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre
    );

    @WebMethod(action = "getHolaMundo")
    @RequestWrapper(localName = "holaMundo", targetNamespace = "http://soap.ws.mochas.ec.com/", className = "ec.com.mochas.testws.HolaMundo")
    @ResponseWrapper(localName = "holaMundoResponse", targetNamespace = "http://soap.ws.mochas.ec.com/", className = "ec.com.mochas.testws.HolaMundoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String holaMundo();
}
