<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns1="http://soap.ws.mochas.ec.com/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.mochas.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TestService" targetNamespace="http://www.mochas.com">
  <wsdl:import location="http://localhost:8080/Test-Web-JEE7/TestService?wsdl=ITestWs.wsdl" namespace="http://soap.ws.mochas.ec.com/">
    </wsdl:import>
  <wsdl:binding name="TestServiceSoapBinding" type="ns1:ITestWs">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="productos">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="productos">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="productosResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="saludar">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="saludar">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="saludarResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InputException">
        <soap:fault name="InputException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="holaMundo">
      <soap:operation soapAction="getHolaMundo" style="document"/>
      <wsdl:input name="holaMundo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="holaMundoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TestService">
    <wsdl:port binding="tns:TestServiceSoapBinding" name="TestPort">
      <soap:address location="http://localhost:8080/Test-Web-JEE7/TestService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
